version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
  - dependency-name: Microsoft.AppCenter.Analytics
    versions:
    - 4.1.0
  - dependency-name: Microsoft.AppCenter.Crashes
    versions:
    - 4.1.0
