name: main-build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Cake Action
        uses: cake-build/cake-action@v1.4.1
        with:
          # The path of the Cake script to run.
          script-path: build.cake
          # The name of the task to execute. Note that this argument must be supported by the script.
          target: Publish
          # The verbosity level with which to run the script. Valid values are: Quiet, Minimal, Normal, Verbose or Diagnostic.
          verbosity: Normal
